---
title: "Human Population Density Data Wrangling"
author: "Claire Meuter and Mia Guarnieri"
date: "2022-10-18"
output: html_document
---

##Setup and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)

#mia and claire's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"

```

#Data Wrangling Prior to Coding

*Data Sources*: Please see ReadMe file for metadata and citations.
*Reference Paper*: Insert hagani citation here

#Load in relevant data layers

##California raster

Insert info about CA raster layer here. Will be used to clip and reproject human population density layer

```{r}

ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Reclassed/CARaster_Tiger_Reclassed.img"))

#check the coordinate reference system 
crs(ca_raster)

#plot CA raster to confirm
tm_shape(ca_raster) +
  tm_raster() +
  tmap_mode("view")

```
