---
title: "Model Creation"
author: "Mia Guarnieri"
date: '2022-10-19'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
#note - Loading all of the ones Jason used, I don't think we will need all of them 

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)

#mia and claire's file path
gdrive_data <- "/Volumes/GoogleDrive/Shared drives/Black_Bear_Aware/gdrive_data"
```

#Data Wrangling Prior to Coding

*Data Sources*: Please see ReadMe file for metadata and citations.
*Reference Paper*: Insert hagani citation here

#Load in relevant data layers

##California raster

Insert info about CA raster layer here

```{r}

ca_raster <- rast(here(gdrive_data, "/IntermediateData/IntermediateData_Files/CARaster_Tiger_Reclassed/CARaster_Tiger_Reclassed.img"))

#check the coordinate reference system 
crs(ca_raster)

#plot CA raster to confirm
tm_shape(ca_raster) +
  tm_raster() +
  tmap_mode("view")

```

#Other

```{r}
#elevation

```

